[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
extend-select = ["I", "PGH", "UP", "N"]
ignore = ["E741"]

[tool.pytest.ini_options]
addopts = ["--cov=weather", "--cov-report=term-missing"]
testpaths = ["tests"]
